import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api/jogo/sidebar';

const sidebars: SidebarsConfig = {
  engenhariaSidebar: [
    {
      type: 'category',
      label: 'Engenharia',
      collapsible: false,
      items: [
        {type: 'autogenerated', dirName: 'visao'},
        {type: 'autogenerated', dirName: 'rf'},
        {type: 'autogenerated', dirName: 'rnf'},
        {type: 'autogenerated', dirName: 'rn'},
        {type: 'autogenerated', dirName: 'uc'},
        {type: 'autogenerated', dirName: 'er'},
        {type: 'autogenerated', dirName: 'adr'},
      ],
    },
  ],
  apiSidebar,
};

export default sidebars;
