import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api/jogo/sidebar';

const sidebars: SidebarsConfig = {
  engenhariaSidebar: [
    {
      type: 'category',
      label: 'Projeto',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'projeto'}],
    },
    {
      type: 'category',
      label: 'Requisitos',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'requisitos'}],
    },
    {
      type: 'category',
      label: 'Modelagem',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'modelagem'}],
    },
    {
      type: 'category',
      label: 'Desenvolvimento',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'desenvolvimento'}],
    },
    {
      type: 'category',
      label: 'Gestão',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'gestao'}],
    },
  ],
  apiSidebar,
};

export default sidebars;